/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bridge;

import bridge.BlockChains.BitcoinChains.QnodecoinChain;
import bridge.common.ConfigObject;
import com.electronwill.nightconfig.core.CommentedConfig;
import com.electronwill.nightconfig.core.Config;
import java.net.MalformedURLException;
import lombok.extern.java.Log;

@Log
public class App {
  public static void main(String[] args) throws MalformedURLException {
    CommentedConfig configObject = ConfigObject.CONFIG;
    double x = configObject.get("Blockchain.Qnodecoin.transfer_fee");
    System.out.println(x);
    QnodecoinChain qnodecoinChain = new QnodecoinChain();
    log.info(qnodecoinChain.getAssetName().toString());
    Config aa = configObject.get("Blockchain.Qnodecoin.asset_name");
    System.out.println(aa.toString());
  }
}
