/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Bridge;

import Bridge.BlockChains.QnodeCoin.QnodecoinChainParams;
import Bridge.common.ConfigParser;
import com.electronwill.nightconfig.core.CommentedConfig;
import com.electronwill.nightconfig.core.conversion.ObjectConverter;

public class App {
  public static void main(String[] args) throws Exception {
    CommentedConfig config = ConfigParser.CONFIG;
    String value = config.get("Blockchain.Qnodecoin.host");
    QnodecoinChainParams objectConverter = new ObjectConverter().toObject(config, QnodecoinChainParams::new);
    System.out.println(value);
    System.out.println(objectConverter.getTransferFee());
    
  }
}
