/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bridge;

import bridge.blockchains.ethchains.BinanceSmartChain;
import bridge.blockchains.ethchains.PolygonChain;
import bridge.blockchains.waves.WavesChain;
import bridge.exceptions.AssetNotFoundException;
import lombok.extern.java.Log;

@Log
public class App {
  public static void main(String[] args) throws AssetNotFoundException {
    PolygonChain<?> polygonChain = new PolygonChain<>("fishfactory_p");
    BinanceSmartChain<?> binanceSmartChain = new BinanceSmartChain<>("qnode_defi");
    WavesChain<?> fishfactoryP = new WavesChain<>("fishfactory_p");
    WavesChain<?> qnodecoinCoin = new WavesChain<>("qnodecoin");

    System.out.println(qnodecoinCoin.getNetworkID().getClass());
    System.out.println(polygonChain.getNetworkNode());
    System.out.println(binanceSmartChain.getChainIdentifier());
    System.out.println(binanceSmartChain.getAssetName());
  }
}
