title = "Bridge Config"

##Note some parameters are blockchian specific, example: network_id

##For all smart contract based blockchains:
#   asset_id: Smart contract address of Token
#   private_key: Deployers private key
#   control_wallet: Deployer's public key

## Generally:
#   chain_identifier: A combination any three ascii characters (A-Z0-9 only).
#                       It is used internally by the bridge.


[Blockchain.Qnodecoin]
asset_name = "Qnodecoin"
ticker_symbol = "QNC"
host = "127.0.0.1"
rpc_port = 20611
rpc_password = "orion.net"
rpc_user = "orion"
network = "mainnet"
control_wallet = "99gsuJ8LoS1fkJED1GMwfFUCcryyaMRKMn"
private_key = "xxxxxxxxxx"
chain_identifier = "QCN"
transfer_fee = 0.0002

[Blockchain.Waves]
asset_name = "Qnodecoin"
ticker_symbol = "QNC"
node = "https://nodes-testnet.wavesnodes.com"
network = "testnet"
network_id = "T"
public_key = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
private_key = "xxxxxxxxxxxxxxxxxxxxxxx"
asset_id = "asset_id"
chain_identifier = "WAV"
transfer_fee = 0.0


[Blockchain.Polygon]
asset_name = "Fishfactory P"
ticker_symbol = "XFP"
node = "sdsd"
network = "sdsd"
control_wallet = "dsd"
private_key = "Polygon-Private-Key" # Deployer Private Key
asset_id = "contract-address"   # Contract Address of toker
chain_identifier = "PLY"
transfer_fee = 0.0

[Blockchain.BSC]
asset_name = "Qnode.Defi"
ticker_symbol = "QND"
network = "testnet"
network_node = "network-node"
control_wallet = "QND-control-Wallet"
contract_address = "QND-contract-adress"
chain_identifier = "BSC"
transfer_fee = 0.0


[Bridge.server]
host = "sdsd"
port = 212

[Bridge.Database]
name = "sds"
host = "sds"
socket = "sds" # if used
port = 232