/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Algorithmic.Bride;

import Bride.App;
import org.junit.jupiter.api.Test;

class AppTest {
  @Test
  void appHasAGreeting() {}
}
