/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Algorithmic.Bride;

import com.lmax.disruptor.dsl.EventProcessorFactory;
import com.lmax.disruptor.dsl.Disruptor;
import org.agrona.BitUtil;
import com.fasterxml.jackson.dataformat.toml.TomlStreamWriteException;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }


    public static <T> void test( T a){
        System.out.println(a);
    }

    public static void main(String[] args) {
        String a = "This is ";
        

    }


}
